site_name: Huiyu CAI
site_description: "Personal website of Huiyu CAI."
repo_name: 'hui2000ji/hui2000ji.github.io'
repo_url: 'https://hui2000ji.github.io'
theme:
  name: material
  features:
    - navigation.tabs
nav:
  - Home: 'index.md'
  - CV: 'assets/documents/CV - Huiyu Cai.pdf'
  - Machine Learning:
    - Index: 'machine_learning/index.md'
    - Graph Neural Networks: 'machine_learning/graph_neural_networks.md'
    - Representation Learning with Mutual Information Maximization: 'machine_learning/representation_learning_with_mutual_information_maximization.md'
  - Single Cell:
    - Review: 'single_cell/review.md'
  # - Python Tutorial: 'python-tutorial/index.md'
markdown_extensions:
  - admonition
  - abbr
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/highlight.min.js
  - assets/js/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/styles/atom-one-light.min.css
  - assets/css/style.css
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:hy_cai@pku.edu.cn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hui2000ji
    - icon: fontawesome/brands/github
      link: https://github.com/hui2000ji
plugins:
    - macros