site_name: Huiyu CAI
theme:
  name: material
  palette:
    scheme: preference
  features:
    - navigation.tabs
nav:
  - Home: 'index.md'
  - CV: 'assets/documents/CV - Huiyu Cai.pdf'
  - Python Tutorial: 'python-tutorial/index.md'
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.6.0/styles/atom-one-light.min.css
extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:hy_cai@pku.edu.cn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hui2000ji
    - icon: fontawesome/brands/github
      link: https://github.com/hui2000ji
plugins:
    - macros